[book]
authors = ["Daniel Mason"]
language = "en"
src = "src"
title = "IRISS Scripts"

[build]
build-dir = "docs"
create-missing = true

[rust]
edition = "2024"

[output.html]
additional-js = ["scripts/enable-checkboxes.js"]
