[package]
name = "without-di"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
fake-database = { path = "../fake-database" }
newtypes = { path = "../newtypes" }
